### ISSUE TITLE
Shuffle feature

### ISSUE THREAD

**Issue by porterga** [cs361fall2017/team3#1]
User story for issue:
-------------------------------------------------------------------------------------------------------------------
Card: As a player, I do not want to see the same order of cards each play through. 

Conversation: 

- The cards will be shuffled before the first four cards are dealt.
- The program will shuffle the cards multiple times to ensure total randomness.
- There will be a message to the player stating that the cards have been shuffled.

Confirmation:

1. The game will be started multiple times, and the first several cards recorded.
- Check and see that there are no consistencies in the first several cards.
- Make sure text that the "cards have been shuffled" is displayed.

2. Display the deck on the terminal to make sure the deck is random.
- On each play-through, display the deck to the terminal to make sure the deck is random on the back end.
- Each time the deck is shuffled, print a notification to the terminal to make sure the deck is being shuffled multiple times. 

-------------------------------------------------------------------------------------------------------------------
Details of the feature:
Make sure the shuffle function randomizes the deck array multiple times. Think about playing cards in real life, you don't just shuffle the deck once, you shuffle it multiple times. 
Display a message to the UI stating that the cards have been shuffled.

Potential sub-feature: Display a message to the UI stating that the cards are being shuffled, so the player knows that the cards are being shuffled. This may add more responsiveness to the game and make it more enjoyable to play.

**Comment by disalvoj** [comment]
this was handled by pull request #8
