### ISSUE TITLE
Remove Feature

### ISSUE THREAD

**Issue by porterga** [cs361fall2017/team3#2]
User story:

-------------------------------------------------------------------------------------------------------------------
Remove

Card: As a player I want to click one of the four columns to remove the top card of that column.

Conversation:

-The user clicks a column and the top card is removed. -The top card is only removed if there is another card of the same suit with a higher value. -If there is an empty column the card is not removed but is instead moved to that column.

Confirmation:

-The user clicks on a column

-Check if the column is empty, if it is empty do nothing

-Check if there is a card of the same suit with a higher value, if there isn't do nothing

-Check if there is an empty column, if there is call move and move the card to the empty column

-Otherwise remove the top card

-After the card has been removed

-Output which card has been removed to console

-Check and make sure the card has been removed

-Check if the deck is now empty

-Refresh the four columns to show them without the removed card

-------------------------------------------------------------------------------------------------------------------
Features:
Deletes the top element of a column based off of an int input telling the function which column to remove from.

**Comment by loughrao** [comment]
I edited your original comment to include my user story
