### ISSUE TITLE
Pressing Space while deal button is in focus deals twice

### ISSUE THREAD

**Issue by Manason** [cs361fall2017/team3#23]
This occurs because dealing cards occurs in two ways:

1) A keylistener hears that spacebar was pressed
2) the deal button is pressed

The default behavior for a button in focus when spacebar is pressed is for that button to be pressed. This causes cards to be dealt both by the keylistener and by the deal button. To fix this, either the default behavior for buttons needs to be changed, or when the deal button is pressed there needs to be a condition that checks that spacebar wasn't the cause.

**Comment by loughrao** [comment]
I will take a look at getting this going as soon as I finish my CSS and fix the remove function, which hopefully will not be too hard.

**Comment by Manason** [comment]
I just tested master and this is still an issue
