### ISSUE TITLE
Clean up CSS

### ISSUE THREAD

**Issue by porterga** [cs361fall2017/team3#42]
Make the CSS modular, it should all look like it was written by the same person. For example, some of our elements have fixed positioning, while some have relative. Everything is slightly different, which makes everything break easily. 

Also, consider using percentages rather than specifying pixels wherever possible, this will make everything break less (hopefully).

**Comment by porterga** [comment]
Also, some of the button positioning needs to be fixed. The column labels are too far above the columns and the the deal button overlaps the columns slightly.

**Comment by Manason** [comment]
There are several issues with the CSS. It probably needs to be redone. Make sure that you are testing that things still look good when the browser is resized.
