### ISSUE TITLE
Column unit test

### ISSUE THREAD

**Issue by porterga** [cs361fall2017/team3#66]
Implement unit test for column.

**Comment by disalvoj** [comment]
For some reason my test seems to not work as intended. I keep getting errors I can't understand or look up.  all of them say "at org.junit.internal.builders.*"

**Comment by Manason** [comment]
Did you already run the setup guide? https://oregonstate.instructure.com/courses/1648342/pages/testing-projects-within-intellij-idea

**Comment by disalvoj** [comment]
Yes and I've compared it with Garen's configuration. everything should work as far as I can tell.
