### ISSUE TITLE
Let user choose Spanish or English version 

### ISSUE THREAD

**Issue by porterga** [cs361fall2017/team3#74]
At the beginning of the game, the user needs to be able to choose between the two decks.

**Comment by porterga** [comment]
I got the modal working, it doesn't look the prettiest, but it works. I am having a hard time changing the deck depending on the selection. I tried making a new SpanishGame class, new spanishReset function, new POST/GET requests, new application controller functions, and new route stuff, but all of this to no avail. Any help is much appreciated!

**Comment by Manason** [comment]
I believe it's Owen's job to update and/or create sub classes for Game and Column to deal with the new Spanish deck functionality. Once he has those completed then the ApplicationController can be updated to return a different version of the Game class depending on the query from the view.

**Comment by loughrao** [comment]
I have completed the game and column functionalities, we can now update the controller
